trigger:
  - none

parameters:
  - name: envlist
    type: string
    displayName: Delimited string env details here

stages:
  - stage: preWork
    jobs: 
     - job: convert_input
       continueOnError: false
       steps: 
         - bash: |
              htring="${{ parameters.envlist }}"
              IFS=', ' read -r -a myArray <<< "$htring"
              echo "##vso[task.setvariable variable=one]${myArray[0]}"
              echo "##vso[task.setvariable variable=two]${myArray[1]}"
              echo "##vso[task.setvariable variable=three]${myArray[2]}"
              echo "##vso[task.setvariable variable=four]${myArray[3]}"
           displayName: "split comma separated to different variables"
         - bash: echo $(one)
           displayName: "echo first variable"
         - bash: echo $(two)
           displayName: "echo second variable"
